xqq/mpegts.js

d.ts/mpegts.d.ts, d.ts/src/demux/base-demuxer.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/patpmt.d.ts, d.ts/src/demux/ts-demuxer.d.ts, docs/api.md, src/core/transmuxer.js, src/core/transmuxing-controller.js, src/core/transmuxing-events.js, src/core/transmuxing-worker.js, src/demux/base-demuxer.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts, src/player/mse-player.js, src/player/player-events.js
Add TIMED_ID3_METADATA_ARRIVED event for HLS timed-id3 data handling.
=> feature: add TIMED_ID3_METADATA_ARRIVED event

d.ts/src/demux/base-demuxer.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/scte35.d.ts, d.ts/src/demux/ts-demuxer.d.ts, docs/api.md, src/core/transmuxer.js, src/core/transmuxing-controller.js, src/core/transmuxing-events.js, src/core/transmuxing-worker.js, src/demux/base-demuxer.ts, src/demux/pat-pmt-pes.ts, src/demux/scte35.ts, src/demux/ts-demuxer.ts, src/player/mse-player.js, src/player/player-events.js
Add SCTE35_METADATA_ARRIVED event for SCTE35 data receiving (just pts_time parse only)
=> feature: add SCTE35_METADATA_ARRIVED

d.ts/src/demux/scte35.d.ts, src/demux/scte35.ts
Improve SCTE35_METADATA_ARRIVED event for SCTE35 monitoring.
=> feature: more details for SCTE35_METADATA_ARRIVED

d.ts/src/demux/h265.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/h264.ts, src/demux/h265-parser.js, src/demux/h265.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts, src/remux/mp4-generator.js
Support H.265 (HEVC) carried by MPEG-TS.
=> feature: H.265(HEVC) support for MPEG-TS

src/demux/flv-demuxer.js
Support for H265 carried by FLV (codecID = 12)
=> feature: H.265(HEVC) support for FLV

d.ts/mpegts.d.ts, d.ts/src/demux/base-demuxer.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/smpte2038.d.ts, d.ts/src/demux/ts-demuxer.d.ts, docs/api.md, src/core/transmuxer.js, src/core/transmuxing-controller.js, src/core/transmuxing-events.js, src/core/transmuxing-worker.js, src/demux/base-demuxer.ts, src/demux/pat-pmt-pes.ts, src/demux/smpte2038.ts, src/demux/ts-demuxer.ts, src/player/mse-player.js, src/player/player-events.js
Support SMPTE2038_METADATA_ARRIVED event for SMPTE-2038 Ancillary Data in MPEG-TS.
=> feature: add SMPTE2038_METADATA_ARRIVED event

d.ts/src/demux/h265.d.ts, src/demux/h265-parser.js, src/demux/h265.ts, src/demux/ts-demuxer.ts
Fix Keyframe Detection for Open-GOP HEVC Stream in HTTP-TS.
=> Fix: fix keyframe for HEVC in HTTP-TS

d.ts/src/demux/mp3.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/mp3.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts
=> Feature: Support mp3 in TS

d.ts/mpegts.d.ts
修复nativeMP4H265Playback 在d.ts 缺失
=> feat:修复d.ts 提示

d.ts/src/demux/h265.d.ts, src/demux/h265-parser.js, src/demux/h265.ts
fix below H.265 issue.
* Fix for refer GeneralLevelIdc for hvcC atom.
* Fix for consider crop offset in hvc1 atom.
* aspect_ratio_idc = 16 missing.
=> Fix: correct hvcC atom

d.ts/src/demux/aac.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/aac.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts
Support LOAS-AAC audio in HTTP-TS
=> Feature: Support LOAS-AAC in MPEG-TS

d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts, src/remux/mp4-generator.js
=> Feature: Support Opus in MPEG-TS

d.ts/src/demux/ac3.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/ac3.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts, src/remux/mp4-generator.js
=> Feature: ATSC AC-3 Support in MPEG-TS

src/demux/flv-demuxer.js
Support H.265(HEVC) FLV by Enhanced RTMP Specification.
=> Feature: Enhanced RTMP HEVC Support in HTTP-FLV

src/demux/h265-parser.js
Fix vui_hrd_parameters indent.
=> Fix: vui_hrd_parameters

d.ts/src/demux/av1-parser.d.ts, src/demux/av1-parser.ts, src/demux/flv-demuxer.js, src/remux/mp4-generator.js
Support AV1 FLV by Enhanced RTMP Specification.
=> Feature: Enhanced RTMP AV1 Support in HTTP-FLV

d.ts/src/demux/ac3.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/ac3.ts, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts, src/remux/mp4-generator.js
=> Feature: ATSC EAC-3 Support in MPEG-TS 

src/demux/h265-parser.js
Fix HEVC sps parse error if hrd_parameter present
=> Fix: HEVC hrd_parameters_present

src/demux/flv-demuxer.js
=> Fix: correct hevc nalutype for FLV

d.ts/src/demux/ts-demuxer.d.ts, src/demux/ts-demuxer.ts
support timestamp wraparound in the middle of mpegts stream
=> feat: support timestamp wraparound

src/demux/flv-demuxer.js, src/remux/mp4-generator.js
=> Feat: Support Opus in FLV

src/demux/flv-demuxer.js, src/remux/mp4-generator.js, src/remux/mp4-remuxer.js
=> Feat: Support FLAC in eFLV

d.ts/src/demux/av1.d.ts, d.ts/src/demux/pat-pmt-pes.d.ts, d.ts/src/demux/ts-demuxer.d.ts, src/demux/av1-parser.ts, src/demux/av1.ts, src/demux/flv-demuxer.js, src/demux/pat-pmt-pes.ts, src/demux/ts-demuxer.ts
Support AV1 in MPEG-TS
* TS in MPEG-TS Support (https://aomediacodec.github.io/av1-mpeg2-ts/)
* Considering Source Aspect Ratio (both FLV, TS)
=> Feat: Support AV1 in MPEG-TS
